
included:
  - CryptoAPI
excluded:
  - CryptoAPI/CryptoAPITests

whitelist_rules:
  - file_header
  - array_init
  - attributes 
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - identical_operands
  - implicit_getter
  - inert_defer
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_random
  - let_var_whitespace
  - line_length
  - mark
  - multiline_literal_brackets
  - nesting
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_setter_value
  - vertical_parameter_alignment
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - type_body_length

file_header:
  severity: error
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  CryptoAPI
                    \/\/
                    \/\/  Created by (Artemy Markovsky|Fedorenko Nikita|Vladimir Sharaev|Alexander Eskin|Dmitry Medyuho) on \d{1,2}(\/|.)\d{1,2}(\/|.)(2019|19|2020|20|2021|21)\.
                    \/\/  Copyright © (2019|2020|2021) PixelPlex\. All rights reserved\.
                    \/\/
                    
identifier_name:
  excluded:
    - id

line_length: 
  warning: 150

file_length: 
  warning: 900
  error: 1000

type_body_length:
  warning: 400
  error: 450

large_tuple: 10

function_body_length: 
  warning: 100
  error: 110

function_parameter_count:
  warning: 10
  error: 15

warning_threshold: 15
