# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :tests do
  desc "Running Unit Tests"
  run_tests(scheme: "CryptoAPI")
end

lane :build do
  desc "Build Framework"
  xcodebuild(
  {
    clean: true,
    build: true,
    scheme: "CryptoAPI",
    sdk: "iphonesimulator",
    destination: "platform=iOS Simulator,name=iPhone 8",
    xcargs: "ONLY_ACTIVE_ARCH=NO"
  }
)
end
