# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'CryptoApiLib-BitcoinKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoApiLib-BitcoinKit

  pod 'CryptoApiLib'
  pod 'BitcoinCore.swift'
  pod 'BitcoinKit.swift'
  pod 'BitcoinCashKit.swift'
  pod 'DashKit.swift'
end
